version: "3.9"
services:
  api:
    build: .
    image: donation-checker-dev
    container_name: donation-checker-api
    volumes:
      - .:/app
      - ./dist:/app/dist
      - "$HOME/.aws:/root/.aws:ro"
    ports:
      - 3000:80
    entrypoint: sh -c "npm install && npm run compile && npm run dev"
