version: "3.9"
services:
  api:
    build: .
    image: donation-checker
    container_name: donation-checker-api
    volumes:
      - .:/app
    ports:
      - 3000:8080
    entrypoint: "npm run start"
